package com.surveymapclient.db.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ANGLE.
 */
public class Angle {

    private Long id;
    private Long key;
    private String name;
    private Float startx;
    private Float starty;
    private Float endx;
    private Float endy;
    private Float anglex;
    private Float angley;
    private Double angle;
    private String desc;
    private Integer pcolor;
    private Float pwidth;
    private Boolean isfull;

    public Angle() {
    }

    public Angle(Long id) {
        this.id = id;
    }

    public Angle(Long id, Long key, String name, Float startx, Float starty, Float endx, Float endy, Float anglex, Float angley, Double angle, String desc, Integer pcolor, Float pwidth, Boolean isfull) {
        this.id = id;
        this.key = key;
        this.name = name;
        this.startx = startx;
        this.starty = starty;
        this.endx = endx;
        this.endy = endy;
        this.anglex = anglex;
        this.angley = angley;
        this.angle = angle;
        this.desc = desc;
        this.pcolor = pcolor;
        this.pwidth = pwidth;
        this.isfull = isfull;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getKey() {
        return key;
    }

    public void setKey(Long key) {
        this.key = key;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Float getStartx() {
        return startx;
    }

    public void setStartx(Float startx) {
        this.startx = startx;
    }

    public Float getStarty() {
        return starty;
    }

    public void setStarty(Float starty) {
        this.starty = starty;
    }

    public Float getEndx() {
        return endx;
    }

    public void setEndx(Float endx) {
        this.endx = endx;
    }

    public Float getEndy() {
        return endy;
    }

    public void setEndy(Float endy) {
        this.endy = endy;
    }

    public Float getAnglex() {
        return anglex;
    }

    public void setAnglex(Float anglex) {
        this.anglex = anglex;
    }

    public Float getAngley() {
        return angley;
    }

    public void setAngley(Float angley) {
        this.angley = angley;
    }

    public Double getAngle() {
        return angle;
    }

    public void setAngle(Double angle) {
        this.angle = angle;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public Integer getPcolor() {
        return pcolor;
    }

    public void setPcolor(Integer pcolor) {
        this.pcolor = pcolor;
    }

    public Float getPwidth() {
        return pwidth;
    }

    public void setPwidth(Float pwidth) {
        this.pwidth = pwidth;
    }

    public Boolean getIsfull() {
        return isfull;
    }

    public void setIsfull(Boolean isfull) {
        this.isfull = isfull;
    }

}
