package com.surveymapclient.db.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table COORDINATE.
 */
public class Coordinate {

    private Long id;
    private Long key;
    private String name;
    private Float xaxisx;
    private Float xaxisy;
    private Float yaxisx;
    private Float yaxisy;
    private Float zaxisx;
    private Float zaxisy;
    private Float centerx;
    private Float centery;
    private Double volum;
    private Float lenght;
    private Float width;
    private Float height;
    private String desc;
    private Integer pcolor;
    private Float pwidth;
    private Boolean isfull;

    public Coordinate() {
    }

    public Coordinate(Long id) {
        this.id = id;
    }

    public Coordinate(Long id, Long key, String name, Float xaxisx, Float xaxisy, Float yaxisx, Float yaxisy, Float zaxisx, Float zaxisy, Float centerx, Float centery, Double volum, Float lenght, Float width, Float height, String desc, Integer pcolor, Float pwidth, Boolean isfull) {
        this.id = id;
        this.key = key;
        this.name = name;
        this.xaxisx = xaxisx;
        this.xaxisy = xaxisy;
        this.yaxisx = yaxisx;
        this.yaxisy = yaxisy;
        this.zaxisx = zaxisx;
        this.zaxisy = zaxisy;
        this.centerx = centerx;
        this.centery = centery;
        this.volum = volum;
        this.lenght = lenght;
        this.width = width;
        this.height = height;
        this.desc = desc;
        this.pcolor = pcolor;
        this.pwidth = pwidth;
        this.isfull = isfull;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getKey() {
        return key;
    }

    public void setKey(Long key) {
        this.key = key;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Float getXaxisx() {
        return xaxisx;
    }

    public void setXaxisx(Float xaxisx) {
        this.xaxisx = xaxisx;
    }

    public Float getXaxisy() {
        return xaxisy;
    }

    public void setXaxisy(Float xaxisy) {
        this.xaxisy = xaxisy;
    }

    public Float getYaxisx() {
        return yaxisx;
    }

    public void setYaxisx(Float yaxisx) {
        this.yaxisx = yaxisx;
    }

    public Float getYaxisy() {
        return yaxisy;
    }

    public void setYaxisy(Float yaxisy) {
        this.yaxisy = yaxisy;
    }

    public Float getZaxisx() {
        return zaxisx;
    }

    public void setZaxisx(Float zaxisx) {
        this.zaxisx = zaxisx;
    }

    public Float getZaxisy() {
        return zaxisy;
    }

    public void setZaxisy(Float zaxisy) {
        this.zaxisy = zaxisy;
    }

    public Float getCenterx() {
        return centerx;
    }

    public void setCenterx(Float centerx) {
        this.centerx = centerx;
    }

    public Float getCentery() {
        return centery;
    }

    public void setCentery(Float centery) {
        this.centery = centery;
    }

    public Double getVolum() {
        return volum;
    }

    public void setVolum(Double volum) {
        this.volum = volum;
    }

    public Float getLenght() {
        return lenght;
    }

    public void setLenght(Float lenght) {
        this.lenght = lenght;
    }

    public Float getWidth() {
        return width;
    }

    public void setWidth(Float width) {
        this.width = width;
    }

    public Float getHeight() {
        return height;
    }

    public void setHeight(Float height) {
        this.height = height;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public Integer getPcolor() {
        return pcolor;
    }

    public void setPcolor(Integer pcolor) {
        this.pcolor = pcolor;
    }

    public Float getPwidth() {
        return pwidth;
    }

    public void setPwidth(Float pwidth) {
        this.pwidth = pwidth;
    }

    public Boolean getIsfull() {
        return isfull;
    }

    public void setIsfull(Boolean isfull) {
        this.isfull = isfull;
    }

}
