package com.surveymapclient.db.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.surveymapclient.db.greendao.Line;
import com.surveymapclient.db.greendao.Polygon;
import com.surveymapclient.db.greendao.Lines;
import com.surveymapclient.db.greendao.Rectangle;
import com.surveymapclient.db.greendao.Coordinate;
import com.surveymapclient.db.greendao.Angle;
import com.surveymapclient.db.greendao.TextNote;
import com.surveymapclient.db.greendao.AudioNote;
import com.surveymapclient.db.greendao.Module;

import com.surveymapclient.db.greendao.LineDao;
import com.surveymapclient.db.greendao.PolygonDao;
import com.surveymapclient.db.greendao.LinesDao;
import com.surveymapclient.db.greendao.RectangleDao;
import com.surveymapclient.db.greendao.CoordinateDao;
import com.surveymapclient.db.greendao.AngleDao;
import com.surveymapclient.db.greendao.TextNoteDao;
import com.surveymapclient.db.greendao.AudioNoteDao;
import com.surveymapclient.db.greendao.ModuleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lineDaoConfig;
    private final DaoConfig polygonDaoConfig;
    private final DaoConfig linesDaoConfig;
    private final DaoConfig rectangleDaoConfig;
    private final DaoConfig coordinateDaoConfig;
    private final DaoConfig angleDaoConfig;
    private final DaoConfig textNoteDaoConfig;
    private final DaoConfig audioNoteDaoConfig;
    private final DaoConfig moduleDaoConfig;

    private final LineDao lineDao;
    private final PolygonDao polygonDao;
    private final LinesDao linesDao;
    private final RectangleDao rectangleDao;
    private final CoordinateDao coordinateDao;
    private final AngleDao angleDao;
    private final TextNoteDao textNoteDao;
    private final AudioNoteDao audioNoteDao;
    private final ModuleDao moduleDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lineDaoConfig = daoConfigMap.get(LineDao.class).clone();
        lineDaoConfig.initIdentityScope(type);

        polygonDaoConfig = daoConfigMap.get(PolygonDao.class).clone();
        polygonDaoConfig.initIdentityScope(type);

        linesDaoConfig = daoConfigMap.get(LinesDao.class).clone();
        linesDaoConfig.initIdentityScope(type);

        rectangleDaoConfig = daoConfigMap.get(RectangleDao.class).clone();
        rectangleDaoConfig.initIdentityScope(type);

        coordinateDaoConfig = daoConfigMap.get(CoordinateDao.class).clone();
        coordinateDaoConfig.initIdentityScope(type);

        angleDaoConfig = daoConfigMap.get(AngleDao.class).clone();
        angleDaoConfig.initIdentityScope(type);

        textNoteDaoConfig = daoConfigMap.get(TextNoteDao.class).clone();
        textNoteDaoConfig.initIdentityScope(type);

        audioNoteDaoConfig = daoConfigMap.get(AudioNoteDao.class).clone();
        audioNoteDaoConfig.initIdentityScope(type);

        moduleDaoConfig = daoConfigMap.get(ModuleDao.class).clone();
        moduleDaoConfig.initIdentityScope(type);

        lineDao = new LineDao(lineDaoConfig, this);
        polygonDao = new PolygonDao(polygonDaoConfig, this);
        linesDao = new LinesDao(linesDaoConfig, this);
        rectangleDao = new RectangleDao(rectangleDaoConfig, this);
        coordinateDao = new CoordinateDao(coordinateDaoConfig, this);
        angleDao = new AngleDao(angleDaoConfig, this);
        textNoteDao = new TextNoteDao(textNoteDaoConfig, this);
        audioNoteDao = new AudioNoteDao(audioNoteDaoConfig, this);
        moduleDao = new ModuleDao(moduleDaoConfig, this);

        registerDao(Line.class, lineDao);
        registerDao(Polygon.class, polygonDao);
        registerDao(Lines.class, linesDao);
        registerDao(Rectangle.class, rectangleDao);
        registerDao(Coordinate.class, coordinateDao);
        registerDao(Angle.class, angleDao);
        registerDao(TextNote.class, textNoteDao);
        registerDao(AudioNote.class, audioNoteDao);
        registerDao(Module.class, moduleDao);
    }
    
    public void clear() {
        lineDaoConfig.getIdentityScope().clear();
        polygonDaoConfig.getIdentityScope().clear();
        linesDaoConfig.getIdentityScope().clear();
        rectangleDaoConfig.getIdentityScope().clear();
        coordinateDaoConfig.getIdentityScope().clear();
        angleDaoConfig.getIdentityScope().clear();
        textNoteDaoConfig.getIdentityScope().clear();
        audioNoteDaoConfig.getIdentityScope().clear();
        moduleDaoConfig.getIdentityScope().clear();
    }

    public LineDao getLineDao() {
        return lineDao;
    }

    public PolygonDao getPolygonDao() {
        return polygonDao;
    }

    public LinesDao getLinesDao() {
        return linesDao;
    }

    public RectangleDao getRectangleDao() {
        return rectangleDao;
    }

    public CoordinateDao getCoordinateDao() {
        return coordinateDao;
    }

    public AngleDao getAngleDao() {
        return angleDao;
    }

    public TextNoteDao getTextNoteDao() {
        return textNoteDao;
    }

    public AudioNoteDao getAudioNoteDao() {
        return audioNoteDao;
    }

    public ModuleDao getModuleDao() {
        return moduleDao;
    }

}
