package com.surveymapclient.db.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RECTANGLE.
 */
public class Rectangle {

    private Long id;
    private Long key;
    private String name;
    private Float startx;
    private Float starty;
    private Float endx;
    private Float endy;
    private Double area;
    private Float lenght;
    private Float width;
    private String desc;
    private Integer pcolor;
    private Float pwidth;
    private Boolean isfull;

    public Rectangle() {
    }

    public Rectangle(Long id) {
        this.id = id;
    }

    public Rectangle(Long id, Long key, String name, Float startx, Float starty, Float endx, Float endy, Double area, Float lenght, Float width, String desc, Integer pcolor, Float pwidth, Boolean isfull) {
        this.id = id;
        this.key = key;
        this.name = name;
        this.startx = startx;
        this.starty = starty;
        this.endx = endx;
        this.endy = endy;
        this.area = area;
        this.lenght = lenght;
        this.width = width;
        this.desc = desc;
        this.pcolor = pcolor;
        this.pwidth = pwidth;
        this.isfull = isfull;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getKey() {
        return key;
    }

    public void setKey(Long key) {
        this.key = key;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Float getStartx() {
        return startx;
    }

    public void setStartx(Float startx) {
        this.startx = startx;
    }

    public Float getStarty() {
        return starty;
    }

    public void setStarty(Float starty) {
        this.starty = starty;
    }

    public Float getEndx() {
        return endx;
    }

    public void setEndx(Float endx) {
        this.endx = endx;
    }

    public Float getEndy() {
        return endy;
    }

    public void setEndy(Float endy) {
        this.endy = endy;
    }

    public Double getArea() {
        return area;
    }

    public void setArea(Double area) {
        this.area = area;
    }

    public Float getLenght() {
        return lenght;
    }

    public void setLenght(Float lenght) {
        this.lenght = lenght;
    }

    public Float getWidth() {
        return width;
    }

    public void setWidth(Float width) {
        this.width = width;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public Integer getPcolor() {
        return pcolor;
    }

    public void setPcolor(Integer pcolor) {
        this.pcolor = pcolor;
    }

    public Float getPwidth() {
        return pwidth;
    }

    public void setPwidth(Float pwidth) {
        this.pwidth = pwidth;
    }

    public Boolean getIsfull() {
        return isfull;
    }

    public void setIsfull(Boolean isfull) {
        this.isfull = isfull;
    }

}
